### ISSUE TITLE
Failed initialization: easy handle already used in multi handle

### ISSUE THREAD

**Issue by nadendlaprasad** [vasild/cpp-ipfs-api#7] opened 2018-12-12 08:48 UTC
Making multiple calls to client.ObjectPut method throwing up  " `Failed initialization: easy handle already used in multi handle` " error. Looks like transport curl not able to handle multiple calls at a time. 

Any idea about this error message ?

FYI: If we make sequential calls it works fine. no issues at all

**Comment by vasild** [comment] 2018-12-12 10:07
> Any idea about this error message ?

Nope.

Do you have a sample prog to demonstrate this?

**Comment by nadendlaprasad** [comment] 2018-12-12 10:59
Here the sample code to re-produce the issue.

```
client=new ipfs::Client("localhost", 5001);		
		client->ObjectPut(input,&object);
		std::thread t([]() {
			ipfs::Json object;
			ipfs::Json input;
			input["Data"] = "my data";
			client->ObjectPut(input, &object);
		});
```

**Comment by nadendlaprasad** [comment] 2018-12-24 13:55
Hi, 

Thanks for your response.


Above program is working fine. I have updated the above program little bit to simulate the issue

```
#include <iostream>
#include <thread>
#include <nlohmann/json.hpp>
#include <ipfs/client.h>
int main()
{
	try {
		ipfs::Client client("localhost", 5001);

		ipfs::Json object_to_store_1 = R"({ "Data": "my data 1" })"_json;
		ipfs::Json object_stored_1;

		client.ObjectPut(object_to_store_1, &object_stored_1);
		std::cout << "Stored object 1:" << std::endl << object_stored_1.dump(2) << std::endl;
		int i = 0;
		while (i < 50) {

			std::thread t([&client,&i]() {
				ipfs::Json object_to_store_2;
				object_to_store_2["Data"] = "my data"+i;
				ipfs::Json object_stored_2;
				try {
					client.ObjectPut(object_to_store_2, &object_stored_2);

					std::cout << "Stored object :"+i << std::endl << object_stored_2.dump(2) << std::endl;
				}
				catch (const std::exception& e) {
					std::cerr << "Error : " << e.what() << std::endl;
				}
			});

			t.detach();
			i++;
		}

		
		while (true) { std::this_thread::sleep_for(std::chrono::seconds(60)); }
	}
	catch (const std::exception& e) {
		std::cerr << "Error 1: " << e.what() << std::endl;
		return 1;
	}
}
```
Hope this code helps to simulate the issue. If not could you please try changing while condition from `i < 10` to `i <100`

I am using,
 ipfs version 0.4.16 
 curl version 7.55.1
OS: Windows 10

**Comment by vasild** [comment] 2018-12-28 14:16
@nadendlaprasad I am able to reproduce the issue. However, the problem comes from the fact that you are using the same `client` object from multiple threads without any protection. That is - you create a `client` object in the main thread, then start a few threads and try to use the same `client` object and its `ObjectPut()` method from those threads. This is not supported. It is like creating a `std::vector` in the main thread, then start a few threads and try to add elements to the vector from the created threads, concurrently.

I modified your example to use a separate `client` object per thread:
```
#include <iostream>
#include <ipfs/client.h>
#include <new>
#include <nlohmann/json.hpp>
#include <string>
#include <thread>
#include <vector>

int main()
{
  try {
    std::vector<std::thread*> threads;
    for (int i = 0; i < 50; ++i) {

      std::thread* t = new std::thread([]() {
        ipfs::Client client("localhost", 5001);

        ipfs::Json object_to_store = R"({ "Data": "my data" })"_json;
        ipfs::Json object_stored;
        try {
          client.ObjectPut(object_to_store, &object_stored);

          std::string msg("Stored object: ");
          msg += "\n";
          msg += object_stored.dump(2);
          msg += "\n";
          std::cout << msg;
        } catch (const std::exception& e) {
          std::string msg("Error from thread: ");
          msg += e.what();
          msg += "\n";
          std::cerr << msg;
        }
      });

      threads.push_back(t);
    }

    for (auto t : threads) {
      t->join();
      delete t;
    }
  } catch (const std::exception& e) {
    std::cerr << "Error global: " << e.what() << std::endl;
    return 1;
  }

  return 0;
}
```

Side note: in your example you are using `"my data"+i` and `"Stored object :"+i` - this is adding an integer to a string and most likely will not do what you intend it to do.

**Comment by vasild** [comment] 2019-01-29 10:49
Closing as the problem is in the way the library is used, not in the library itself.

**Closed by vasild** 2019-01-29 10:49 UTC
