### ISSUE TITLE
ObjectData function not thread safe

### ISSUE THREAD

**Issue by Florian-BACHO** [vasild/cpp-ipfs-api#12] opened 2019-08-07 11:25 UTC
The following code demonstrate that the ObjectData function is not thread safe and throws std::runtime_error exception.

```c++
#include <thread>
#include <ipfs/client.h>

int main()
{
        auto hash = "QmcXneAawME7d3vmV3x95p3WVxczeTid7LpJW8DcH4sA5c";
        ipfs::Client ipfs("localhost", 5001);
        std::thread t1([&hash, &ipfs]() { std::string data; ipfs.ObjectData(hash, &data); });
        std::thread t2([&hash, &ipfs]() { std::string data; ipfs.ObjectData(hash, &data); });

        t1.join();
        t2.join();
        return (0);
}
```

On MacOS:
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed initialization`

**Comment by vasild** [comment] 2019-09-25 10:31
Hi,

You are using the same `ipfs::Client` object concurrently from two different threads without providing any synchronization. That is not supported. You would get similar result with e.g.:
```
        std::string s("abcd");
        std::thread t1([&s]() { s.append("x"); });
        std::thread t2([&s]() { s.append("y"); });
```

Closing as not a bug.

**Closed by vasild** 2019-09-25 10:31 UTC

**Comment by danger89** [comment] 2022-01-06 23:42
@Florian-BACHO I don't know if you are still using IPFS and/or C++ IPFS HTTP Client.

But I made some changes under the hood. Allowing to execute the calls within a thread, including to terminate the request early.

See [the example]( https://github.com/vasild/cpp-ipfs-http-client/blob/861db76e91a40fd4c80c6ba928217e2a9654ed2b/examples/threading_example.cc) in the commit.

See be part of the [examples page on Doxygen](https://vasild.github.io/cpp-ipfs-http-client/examples.html)
